apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: rick-and-morty-characters-api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: 5000
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: 5000
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
