name: Deploy to Kubernetes with Minikube

on:
  push:
    branches:
      - main

jobs:
  setup-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/
          minikube start --driver=docker

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

  deploy-app:
    runs-on: ubuntu-latest
    needs: setup-cluster
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Configure kubectl for Minikube
        run: |
          kubectl config use-context minikube

      - name: Deploy with Helm
        run: |
          helm upgrade --install my-app ./helm --namespace default --create-namespace

  test-endpoints:
    runs-on: ubuntu-latest
    needs: deploy-app
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python -m pip install -r app/requirements.txt

      - name: Run Tests
        run: python tests/test_endpoints.py
